# -*- coding: utf-8 -*-
"""Data_Visualization_Case_Study.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1-4d8_ZwmeNRAB6pC22_SNJAaxJL9Vc8l
"""

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

sns.set_style("whitegrid")
plt.rcParams["figure.figsize"] = (8, 5)

df = sns.load_dataset("penguins")
df.head()

print("Shape of dataset:", df.shape)
print("\nColumn names:")
print(df.columns)

print("\nDataset info:")
print(df.info())

print("\nMissing values:")
print(df.isnull().sum())

print("\nSummary statistics:")
print(df.describe())

# Remove missing values
df = df.dropna()

print("Shape after removing missing values:", df.shape)
print("\nRemaining missing values:")
print(df.isnull().sum())

print("Species:", df["species"].unique())
print("Islands:", df["island"].unique())
print("Sex:", df["sex"].unique())

plt.figure()
sns.histplot(df["body_mass_g"], kde=True)
plt.title("Distribution of Body Mass")
plt.xlabel("Body Mass (g)")
plt.ylabel("Frequency")
plt.show()

plt.figure()
sns.countplot(x="species", data=df)
plt.title("Count of Penguins by Species")
plt.xlabel("Species")
plt.ylabel("Count")
plt.show()

plt.figure()
sns.boxplot(y="flipper_length_mm", data=df)
plt.title("Box Plot of Flipper Length")
plt.ylabel("Flipper Length (mm)")
plt.show()

plt.figure()
sns.scatterplot(
    x="bill_length_mm",
    y="bill_depth_mm",
    hue="species",
    data=df
)
plt.title("Bill Length vs Bill Depth")
plt.xlabel("Bill Length (mm)")
plt.ylabel("Bill Depth (mm)")
plt.show()

plt.figure()
sns.barplot(x="species", y="body_mass_g", data=df)
plt.title("Average Body Mass by Species")
plt.xlabel("Species")
plt.ylabel("Average Body Mass (g)")
plt.show()

plt.figure()
sns.boxplot(x="sex", y="body_mass_g", data=df)
plt.title("Body Mass Distribution by Sex")
plt.xlabel("Sex")
plt.ylabel("Body Mass (g)")
plt.show()

plt.figure()
sns.boxplot(x="species", y="body_mass_g", hue="sex", data=df)
plt.title("Body Mass by Species and Sex")
plt.xlabel("Species")
plt.ylabel("Body Mass (g)")
plt.show()

sns.pairplot(df, hue="species")
plt.show()

plt.figure(figsize=(8, 6))
numeric_df = df.select_dtypes(include=["float64", "int64"])
corr = numeric_df.corr()

sns.heatmap(corr, annot=True, cmap="coolwarm", fmt=".2f")
plt.title("Correlation Heatmap")
plt.show()

grouped = df.groupby("species")[["bill_length_mm", "bill_depth_mm", "flipper_length_mm", "body_mass_g"]].mean()
print(grouped)

plt.figure(figsize=(8, 5))
sns.heatmap(grouped, annot=True, cmap="YlGnBu", fmt=".1f")
plt.title("Average Measurements by Species")
plt.xlabel("Features")
plt.ylabel("Species")
plt.show()